table: src_rrhh_evaluaciones
schema: raw

columns:
  - name: sistema_origen
    type: TEXT
    nullable: true
  - name: fecha_extraccion
    type: DATE
    nullable: true
  - name: nro_linea_archivo
    type: INTEGER
    nullable: true
  - name: legajo
    type: INTEGER
    nullable: true
  - name: nombre
    type: TEXT
    nullable: true
  - name: apellido
    type: TEXT
    nullable: true
  - name: departamento_codigo
    type: TEXT
    nullable: true
  - name: anio_evaluacion
    type: INTEGER
    nullable: true
  - name: resultado_evaluacion
    type: TEXT
    nullable: true

indexes:
  - columns: legajo
    unique: false
  - columns: departamento_codigo
    unique: false
  - columns: anio_evaluacion
    unique: false